language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-support
  - extra-android-m2repository
env:
  global:
  - IJK_HASH=k0.8.4
  - IJK_REPO=https://github.com/Bilibili/ijkplayer.git
  - secure: AMEfVUKVjl1KRYslvISLGMf1cuWtP6gNX8crk0f77SikAVzAgucPe8EJ/oXoz0CCOQQErdrHVHAURTz+MJaBdGeqy5P4aDHCLWVbNyDAwzh4vOCjX0L+QeyRCCxKjiibXOK+2kBFCy/i2x+x4QbwHePwqvtEUG/1Y6pyVyuO7sdZKo0vPSqYYzuJ7OD1S5CQMzKUOwKRign3X9SoG7IyzHTlU9KpM7J8Irhs6N/bNVI/RoREps/rm1eFoDgboohmOMrdiS9xkV9UdcoEGicBU7KYRUuqxKx5Qrk+s7GRqHgMbgX00kbNX35s56xyxfPSvbfX3tTarcHhiOOiaZ7du3rbRLq6SaBDq2yIfBoPT6StdBHkG0WuPfARiVXtegmgZcWJIloDbmD8iLVS0s7yF3trPLwgwHw/Dmc+SstoCOyk0suutsrOSwqGvRACqfRTwR09ErkEzPY68tpP+9X/pTgiQHVTiDL2jBicvUCU6kvs+IwBbv+motuCNVC0Bcl/fIgHO60sts5R1TAT2SpWMs24Hi0Y5fGPJvz5UTS62f+dbUnzm0b+exa8OB35A4owfoTg83ymJ1IwblDfmW68NldZz0xhONBuj4pJYcPVtqV6y2P8GgjmId7C4ukVYLe750NgRE94zqHWL+nRHorrOd04eYohz/uoCOADVKWiHi8=
  - secure: j2lgCDazPCsJytCnr/gu1s7bgw3z+Dcvtqcl9jqmvFKSomHFNsDCY5tzU3P2G5meDlieFWJN1e/KYl9oinW1ORuB1A+3TODkUOsGvA+EQogy2IBs3iKAT58LA7SjYCkxPuV0Bi3JgzR5KaXmgl7ZVTGY3f8x3sldI1IT6Y8USjfXpsIxPZuUTuTOk0LPWR8iWSGWppLhUtQH0G4UqV3zOJpNNxyhZ5gD1JtAcfvXal1d6DAiTYKnHlSYhMmDNIvvZX24jX+pFkh1tvGJ6k6KyQOG+oX1TEFpaTwtavT2j4JyULmn//xzU5rZcQ31GSA+DfoY1fBenmZw+jF0omluIqsGPfF+4WdaYdCwFscuWLHxEGsmqb5dFglrtN2qN5V3HdhV3tKkbcitZK0Q8XN+g1/9C+NU+G2zrQGeE0cDPPCP+ZXx4yc5WtLjxzbma4yrixXsc7WCDzIRjKx6DodO7SOOMg4yVYmBKQQN+mrL6TYfhAW1b3fetypdvTm5nvnhA6m+UUXH/uVAiy9aSb+snhFwntukDfgPhgv7TM2lQx5hmab//wrU4xKmKbqjv2g+hRAvJD7HuFMLtNsxzcMKgpsY273o76zaEvOSmHUh0OEa/Fuem8eyaTHgZE1OyC929fybRTQd88SOnx8A0Oo8E8cIzvZVnG1BZr7NHVs7bvw=
  - secure: ULZGzwpRzkEODKDRsiOFD7SZkiymMsIm9uuIC3EyNVQQkU29l/5Oy4WFvNubeZ+Dbuz5bIsDmdiL0NT56O+hu6+UrDAoU1dTXx49Om25ZlWTJe/Fte39an50KSezuGmAxy8AqDHvPumrM/uPY/a+rUg0YgttYKhcIlwZbOfSr+JJXBUDlU8aOu6cl6Mbuh6P6Iq2p8CSlaQpoGFS72AUWWTdnWczcy7N7d13XZC4Qy+2D2/opGmSaGUnABNXyQC7aKB8xKI2fx1qNq7d2FCMenSm2Ft9dMwvsyFBgWmYMH0y2q1lg0x5uoG8jV8bmEqSp5IheVm7mF56pheMUQXJRWmSzNdV1EOFZ3Saao8PAW1OYj/xaZxuu76Rw5w1rVorxJiWQG9uGGzK8E8q0o4xkWxEFUBPATVwve0gkba66xH3ifNumbLBoWJgiS3Bpx+XJdmZ6ZkCen9Os1oLSgHzdNtCML40AFo3cqckN9l+QoD/zeF9XhcLM6cIFBg4uXC9DQST2dHnwrrhmI0Tet3mtX4IEL99iCfpmD8+lAhPYK8PWbNgUiF9h1BG+7osM3yPjSEW9ETLKaBdaH+VsvpU2ZtWWf0elOrc5c053CuHYYOiKz+wMAXRjybugNL2UYza9gJ+aUcs6HdBaIihdD6AZwGv3Z6nuKFJ/LHR3KT38y8=
before_install:
- sudo apt-get install -y git
- sudo apt-get install -y yasm
- jdk_switcher use oraclejdk8
before_script:
- wget "https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip"
- mkdir -p $HOME/android-ndk-root
- unzip android-ndk-r10e-linux-x86_64.zip -d $HOME/android-ndk-root > /dev/null
- export ANDROID_NDK=$HOME/android-ndk-root/android-ndk-r10e
- git clone --depth=50 --branch=$IJK_HASH $IJK_REPO
- cd ijkplayer
- "./init-android.sh"
- cd android
- "./build-on-travis.sh all"
script:
- echo "FINISHED"
